version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: "hello"
      POSTGRES_USER: "hello"
      POSTGRES_PASSWORD: "hello"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
